export interface LanguageOption {
  code: string;       // Primary i18n key (e.g., 'en', 'pt', 'es')
  subtag: string;     // Full ISO subtag (e.g., 'en-US', 'pt-BR')
  originalName: string; // Native name of the language (e.g., 'English')
  translatedName: string; // Display name with variant (e.g., 'English (US)')
  country: string;    // Main country name
  flag: string;       // Country flag emoji
  priority: 'premium' | 'growth' | 'global';
}

export const languagesList: LanguageOption[] = [
  // --- Mercados Premium ---
  {
    code: 'en',
    subtag: 'en-US',
    originalName: 'English',
    translatedName: 'English (US)',
    country: 'United States',
    flag: '🇺🇸',
    priority: 'premium',
  },
  {
    code: 'en',
    subtag: 'en-GB',
    originalName: 'English',
    translatedName: 'English (UK)',
    country: 'United Kingdom',
    flag: '🇬🇧',
    priority: 'premium',
  },
  {
    code: 'en',
    subtag: 'en-CA',
    originalName: 'English',
    translatedName: 'English (Canada)',
    country: 'Canada',
    flag: '🇨🇦',
    priority: 'premium',
  },
  {
    code: 'en',
    subtag: 'en-AU',
    originalName: 'English',
    translatedName: 'English (Australia)',
    country: 'Australia',
    flag: '🇦🇺',
    priority: 'premium',
  },
  {
    code: 'pt',
    subtag: 'pt-BR',
    originalName: 'Português',
    translatedName: 'Português (Brasil)',
    country: 'Brasil',
    flag: '🇧🇷',
    priority: 'premium',
  },
  {
    code: 'es',
    subtag: 'es-ES',
    originalName: 'Español',
    translatedName: 'Español (España)',
    country: 'España',
    flag: '🇪🇸',
    priority: 'premium',
  },
  {
    code: 'es',
    subtag: 'es-MX',
    originalName: 'Español',
    translatedName: 'Español (México)',
    country: 'México',
    flag: '🇲🇽',
    priority: 'premium',
  },
  {
    code: 'fr',
    subtag: 'fr-FR',
    originalName: 'Français',
    translatedName: 'Français',
    country: 'França',
    flag: '🇫🇷',
    priority: 'premium',
  },
  {
    code: 'de',
    subtag: 'de-DE',
    originalName: 'Deutsch',
    translatedName: 'Deutsch',
    country: 'Alemanha',
    flag: '🇩🇪',
    priority: 'premium',
  },
  {
    code: 'it',
    subtag: 'it-IT',
    originalName: 'Italiano',
    translatedName: 'Italiano',
    country: 'Itália',
    flag: '🇮🇹',
    priority: 'premium',
  },
  {
    code: 'nl',
    subtag: 'nl-NL',
    originalName: 'Nederlands',
    translatedName: 'Nederlands',
    country: 'Países Baixos',
    flag: '🇳🇱',
    priority: 'premium',
  },

  // --- Mercados em Crescimento ---
  {
    code: 'ja',
    subtag: 'ja-JP',
    originalName: '日本語',
    translatedName: '日本語',
    country: 'Japão',
    flag: '🇯🇵',
    priority: 'growth',
  },
  {
    code: 'ko',
    subtag: 'ko-KR',
    originalName: '한국어',
    translatedName: '한국어',
    country: 'Coreia do Sul',
    flag: '🇰🇷',
    priority: 'growth',
  },
  {
    code: 'zh',
    subtag: 'zh-CN',
    originalName: '中文',
    translatedName: '简体中文',
    country: 'China',
    flag: '🇨🇳',
    priority: 'growth',
  },
  {
    code: 'hi',
    subtag: 'hi-IN',
    originalName: 'हिन्दी',
    translatedName: 'हिन्दी',
    country: 'Índia',
    flag: '🇮🇳',
    priority: 'growth',
  },
  {
    code: 'tr',
    subtag: 'tr-TR',
    originalName: 'Türkçe',
    translatedName: 'Türkçe',
    country: 'Turquia',
    flag: '🇹🇷',
    priority: 'growth',
  },
  {
    code: 'pl',
    subtag: 'pl-PL',
    originalName: 'Polski',
    translatedName: 'Polski',
    country: 'Polônia',
    flag: '🇵🇱',
    priority: 'growth',
  },
  {
    code: 'sv',
    subtag: 'sv-SE',
    originalName: 'Svenska',
    translatedName: 'Svenska',
    country: 'Suécia',
    flag: '🇸🇪',
    priority: 'growth',
  },
  {
    code: 'no',
    subtag: 'no-NO',
    originalName: 'Norsk',
    translatedName: 'Norsk',
    country: 'Noruega',
    flag: '🇳🇴',
    priority: 'growth',
  },
  {
    code: 'da',
    subtag: 'da-DK',
    originalName: 'Dansk',
    translatedName: 'Dansk',
    country: 'Dinamarca',
    flag: '🇩🇰',
    priority: 'growth',
  },
  {
    code: 'fi',
    subtag: 'fi-FI',
    originalName: 'Suomi',
    translatedName: 'Suomi',
    country: 'Finlândia',
    flag: '🇫🇮',
    priority: 'growth',
  },
  {
    code: 'ru',
    subtag: 'ru-RU',
    originalName: 'Русский',
    translatedName: 'Русский',
    country: 'Rússia',
    flag: '🇷🇺',
    priority: 'growth',
  },

  // --- Expansão Global ---
  {
    code: 'pt',
    subtag: 'pt-PT',
    originalName: 'Português',
    translatedName: 'Português (Portugal)',
    country: 'Portugal',
    flag: '🇵🇹',
    priority: 'global',
  },
  {
    code: 'es',
    subtag: 'es-AR',
    originalName: 'Español',
    translatedName: 'Español (Argentina)',
    country: 'Argentina',
    flag: '🇦🇷',
    priority: 'global',
  },
  {
    code: 'es',
    subtag: 'es-CL',
    originalName: 'Español',
    translatedName: 'Español (Chile)',
    country: 'Chile',
    flag: '🇨🇱',
    priority: 'global',
  },
  {
    code: 'es',
    subtag: 'es-CO',
    originalName: 'Español',
    translatedName: 'Español (Colômbia)',
    country: 'Colômbia',
    flag: '🇨🇴',
    priority: 'global',
  },
  {
    code: 'es',
    subtag: 'es-PE',
    originalName: 'Español',
    translatedName: 'Español (Peru)',
    country: 'Peru',
    flag: '🇵🇪',
    priority: 'global',
  },
  {
    code: 'es',
    subtag: 'es-UY',
    originalName: 'Español',
    translatedName: 'Español (Uruguai)',
    country: 'Uruguai',
    flag: '🇺🇾',
    priority: 'global',
  },
  {
    code: 'es',
    subtag: 'es-VE',
    originalName: 'Español',
    translatedName: 'Español (Venezuela)',
    country: 'Venezuela',
    flag: '🇻🇪',
    priority: 'global',
  },
  {
    code: 'el',
    subtag: 'el-GR',
    originalName: 'Ελληνικά',
    translatedName: 'Ελληνικά',
    country: 'Grécia',
    flag: '🇬🇷',
    priority: 'global',
  },
  {
    code: 'cs',
    subtag: 'cs-CZ',
    originalName: 'Čeština',
    translatedName: 'Čeština',
    country: 'Chéquia',
    flag: '🇨🇿',
    priority: 'global',
  },
  {
    code: 'ro',
    subtag: 'ro-RO',
    originalName: 'Română',
    translatedName: 'Română',
    country: 'Romênia',
    flag: '🇷🇴',
    priority: 'global',
  },
  {
    code: 'hu',
    subtag: 'hu-HU',
    originalName: 'Magyar',
    translatedName: 'Magyar',
    country: 'Hungria',
    flag: '🇭🇺',
    priority: 'global',
  },
  {
    code: 'th',
    subtag: 'th-TH',
    originalName: 'ไทย',
    translatedName: 'ไทย',
    country: 'Tailândia',
    flag: '🇹🇭',
    priority: 'global',
  },
  {
    code: 'vi',
    subtag: 'vi-VN',
    originalName: 'Tiếng Việt',
    translatedName: 'Tiếng Việt',
    country: 'Vietnã',
    flag: '🇻🇳',
    priority: 'global',
  },
  {
    code: 'id',
    subtag: 'id-ID',
    originalName: 'Bahasa Indonesia',
    translatedName: 'Bahasa Indonesia',
    country: 'Indonésia',
    flag: '🇮🇩',
    priority: 'global',
  },
  {
    code: 'ms',
    subtag: 'ms-MY',
    originalName: 'Bahasa Melayu',
    translatedName: 'Bahasa Melayu',
    country: 'Malásia',
    flag: '🇲🇾',
    priority: 'global',
  },
  {
    code: 'ar',
    subtag: 'ar-SA',
    originalName: 'العربية',
    translatedName: 'العربية',
    country: 'Arábia Saudita',
    flag: '🇸🇦',
    priority: 'global',
  },
  {
    code: 'he',
    subtag: 'he-IL',
    originalName: 'עברית',
    translatedName: 'עברית',
    country: 'Israel',
    flag: '🇮🇱',
    priority: 'global',
  },
  {
    code: 'uk',
    subtag: 'uk-UA',
    originalName: 'Українська',
    translatedName: 'Українська',
    country: 'Ucrânia',
    flag: '🇺🇦',
    priority: 'global',
  }
];

export function searchLanguages(query: string): LanguageOption[] {
  if (!query) return languagesList;
  const cleanQuery = query.toLowerCase().trim();
  return languagesList.filter(lang => 
    lang.country.toLowerCase().includes(cleanQuery) ||
    lang.originalName.toLowerCase().includes(cleanQuery) ||
    lang.translatedName.toLowerCase().includes(cleanQuery) ||
    lang.code.toLowerCase().includes(cleanQuery) ||
    lang.subtag.toLowerCase().includes(cleanQuery)
  );
}
